version = 0.1

[default]
[default.deploy]
stack_name = "recce-dev-stack"
s3_bucket = "lambdadeploymenttest07022025"
s3_prefix = "recce-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=recce-dev"
confirm_changeset = true
disable_rollback = false
image_repositories = []
resolve_s3 = true
s3_force_path_style = true

[default.build]
use_container = true
cached = true
parallel = true

[recce-prod]
[recce-prod.deploy]
stack_name = "recce-prod-stack"
s3_bucket = "lamndaenv"
s3_prefix = "recce-prod"
region = "ap-south-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=recce-prod"
confirm_changeset = true
fail_on_empty_changeset = false
image_repositories = []
resolve_s3 = true
s3_force_path_style = true

[recce-prod.build]
use_container = true
cached = true
parallel = true
