service: multi-lambda-service
provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1

functions:
  function1:
    handler: function1/index.handler
    events:
      - http:
          path: function1
          method: get

  function2:
    handler: function2/index.handler
    events:
      - http:
          path: function2
          method: get

plugins:
  - serverless-webpack
