AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 128
    Timeout: 30
    Runtime: nodejs20.x
    Layers:
      - !Ref MyCommonLayer  # Attach default layer to all Lambda functions

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: reccelambdaiamrole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::715499049821:policy/SSMforLAMBDA

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods: ['GET', 'POST', 'PUT', 'DELETE']
        AllowHeaders: ['Content-Type']
        AllowOrigins: ['*']

  Function1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Function1
      Handler: function1/index.handler
      CodeUri: functions/function1
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi  # Explicitly attach to MyHttpApi
            Path: /function1
            Method: any

  Function2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Function2
      Handler: function2/index.handler
      CodeUri: functions/function2
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi  # Explicitly attach to MyHttpApi
            Path: /function2
            Method: any

  Function3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Function3
      Handler: function3/index.handler
      CodeUri: functions/function3
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi  # Explicitly attach to MyHttpApi
            Path: /function3
            Method: any

  MyCommonLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: my-common-layer
      Description: Common dependencies layer with centralized .env
      ContentUri: layers/my-common-layer
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

Outputs:
  HttpApiEndpoint:
    Description: API Gateway HTTP API endpoint URL
    Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
