AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 128
    Timeout: 30
    Runtime: nodejs20.x

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  Function1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: function1/index.handler
      CodeUri: functions/function1
      Role: !GetAtt LambdaExecutionRole.Arn

  Function2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: function1/index.handler
      CodeUri: functions/function1
      Role: !GetAtt LambdaExecutionRole.Arn

  Function3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: function1/index.handler
      CodeUri: functions/function1
      Role: !GetAtt LambdaExecutionRole.Arn

  MyCommonLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: my-common-layer
      Description: Common dependencies layer
      ContentUri: layers/my-common-layer
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain
