name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV=recce-prod" >> $GITHUB_ENV
            echo "S3_BUCKET=lambdadeployment-prod" >> $GITHUB_ENV
            echo "STACK_NAME=recce-prod" >> $GITHUB_ENV
          else
            echo "ENV=recce-dev" >> $GITHUB_ENV
            echo "S3_BUCKET=lambdadeployment-dev" >> $GITHUB_ENV
            echo "STACK_NAME=recce-dev" >> $GITHUB_ENV
          fi

      - name: Build layers
        run: |
          if [ -d "layers/my-common-layer" ]; then
            mkdir -p layers/my-common-layer/nodejs
            cp layers/my-common-layer/package.json layers/my-common-layer/nodejs/
            cd layers/my-common-layer/nodejs
            npm install
            cd ../../..
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: SAM build
        run: sam build --parameter-overrides Environment=${{ env.ENV }}

      - name: Package and Deploy
        run: |
          sam package \
            --output-template-file packaged.yaml \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --region ap-south-1

          sam deploy \
            --template-file packaged.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --region ap-south-1 \
            --parameter-overrides Environment=${{ env.ENV }} \
            --no-fail-on-empty-changeset
