name: Deploy Lambda Function

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the function
        run: npm run build # Add a build script if necessary

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1' 

      - name: Deploy to Lambda
        uses: aws-actions/aws-lambda-deploy@v4
        with:
          s3-bucket: lambdadeploymenttest07022025  # Replace with your S3 bucket name
          function-name: hello1 # Replace with your Lambda function name
          package-type: zip
          zip-file: dist.zip # Replace with the path to your zipped function